spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: "jdbc:mariadb://localhost:3306/travel?allowPublicKeyRetrieval=true&useSSL=false"
        username: root
        password: zxc74100